version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
    - method: setuptools
      path: another/package
  system_packages: true
